<a href="https://colab.research.google.com/github/gaurav-vyas34/-smart-energy-analytics-intern/blob/main/AboutData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [10]:
df = pd.read_csv('household_power_consumption.txt',
                  sep=';',           # semicolon separator
                  na_values='?',     # treat ? as missing
                  low_memory=False,
                  parse_dates={'datetime': ['Date', 'Time']},  # combine date+time
                  dayfirst=True)     # date format is DD/MM/YYYY

/tmp/ipykernel_3295/3795958351.py:1: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  df = pd.read_csv('household_power_consumption.txt',

In [11]:
df.shape

(2075259, 8)

In [12]:
df.head()

,datetime,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2006-12-16 17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0
1,2006-12-16 17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,2006-12-16 17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,2006-12-16 17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
4,2006-12-16 17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075259 entries, 0 to 2075258
Data columns (total 8 columns):
 #   Column                 Dtype
---  ------                 -----
 0   datetime               datetime64[ns]
 1   Global_active_power    float64
 2   Global_reactive_power  float64
 3   Voltage                float64
 4   Global_intensity       float64
 5   Sub_metering_1         float64
 6   Sub_metering_2         float64
 7   Sub_metering_3         float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 126.7 MB

In [14]:
df.describe()

,datetime,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
count,2075259,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06,2.049280e+06
mean,2008-12-06 07:12:59.999994112,1.091615e+00,1.237145e-01,2.408399e+02,4.627759e+00,1.121923e+00,1.298520e+00,6.458447e+00
min,2006-12-16 17:24:00,7.600000e-02,0.000000e+00,2.232000e+02,2.000000e-01,0.000000e+00,0.000000e+00,0.000000e+00
25%,2007-12-12 00:18:30,3.080000e-01,4.800000e-02,2.389900e+02,1.400000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2008-12-06 07:13:00,6.020000e-01,1.000000e-01,2.410100e+02,2.600000e+00,0.000000e+00,0.000000e+00,1.000000e+00
75%,2009-12-01 14:07:30,1.528000e+00,1.940000e-01,2.428900e+02,6.400000e+00,0.000000e+00,1.000000e+00,1.700000e+01
max,2010-11-26 21:02:00,1.112200e+01,1.390000e+00,2.541500e+02,4.840000e+01,8.800000e+01,8.000000e+01,3.100000e+01
std,NaN,1.057294e+00,1.127220e-01,3.239987e+00,4.444396e+00,6.153031e+00,5.822026e+00,8.437154e+00

In [15]:
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())

Shape: (2075259, 8)

Columns: ['datetime', 'Global_active_power', 'Global_reactive_power', 'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3']

In [16]:
print("Missing Values:")
print(df.isnull().sum())
print("\nMissing %:")
print((df.isnull().sum() / len(df) * 100).round(2))

Missing Values:
datetime                     0
Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
Sub_metering_2           25979
Sub_metering_3           25979
dtype: int64

Missing %:
datetime                 0.00
Global_active_power      1.25
Global_reactive_power    1.25
Voltage                  1.25
Global_intensity         1.25
Sub_metering_1           1.25
Sub_metering_2           1.25
Sub_metering_3           1.25
dtype: float64

In [17]:
print(df.describe())

                            datetime  Global_active_power  \
count                        2075259         2.049280e+06
mean   2008-12-06 07:12:59.999994112         1.091615e+00
min              2006-12-16 17:24:00         7.600000e-02
25%              2007-12-12 00:18:30         3.080000e-01
50%              2008-12-06 07:13:00         6.020000e-01
75%              2009-12-01 14:07:30         1.528000e+00
max              2010-11-26 21:02:00         1.112200e+01
std                              NaN         1.057294e+00

       Global_reactive_power       Voltage  Global_intensity  Sub_metering_1  \
count           2.049280e+06  2.049280e+06      2.049280e+06    2.049280e+06
mean            1.237145e-01  2.408399e+02      4.627759e+00    1.121923e+00
min             0.000000e+00  2.232000e+02      2.000000e-01    0.000000e+00
25%             4.800000e-02  2.389900e+02      1.400000e+00    0.000000e+00
50%             1.000000e-01  2.410100e+02      2.600000e+00    0.000000e+00
75%             1.940000e-01  2.428900e+02      6.400000e+00    0.000000e+00
max             1.390000e+00  2.541500e+02      4.840000e+01    8.800000e+01
std             1.127220e-01  3.239987e+00      4.444396e+00    6.153031e+00

       Sub_metering_2  Sub_metering_3
count    2.049280e+06    2.049280e+06
mean     1.298520e+00    6.458447e+00
min      0.000000e+00    0.000000e+00
25%      0.000000e+00    0.000000e+00
50%      0.000000e+00    1.000000e+00
75%      1.000000e+00    1.700000e+01
max      8.000000e+01    3.100000e+01
std      5.822026e+00    8.437154e+00